-- ============================================================
-- TaskFlow INACAP · Auditoría externa con Supabase (rama dev)
-- ============================================================
-- Ejecuta este script en el SQL Editor de tu proyecto Supabase
-- (Dashboard > SQL Editor > New query) para crear la tabla de
-- auditoría que recibe los eventos de tasks/services.py.
-- ============================================================

create table if not exists task_audit_log (
  id bigint generated by default as identity primary key,
  task_id integer not null,
  task_title text not null,
  action text not null,
  user_username text not null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS y política de inserción pública con anon key si aplica.
alter table task_audit_log enable row level security;

create policy "Permitir inserción anónima de logs"
on task_audit_log for insert
to anon
with check (true);

-- Índice útil para consultar el historial por tarea.
create index if not exists task_audit_log_task_id_idx on task_audit_log (task_id);
